Fixed linting
hatchways/team-shiba pull request #40
Opened 2021-06-14 18:30 UTC by grayey

### What this PR does (required):
- This fixes the linting error that occurs the client area. The now builds successfully.

### Screenshots / Videos (required):
![image](https://user-images.githubusercontent.com/26135612/121941083-c0253200-cd46-11eb-8717-f1864d15204c.png)

### Any information needed to test this feature (required):
- Pull changes and run "npm run start"

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-06-16 01:16 UTC, bonnieli commented on server/sample.env
> +MONGO_URI=mongodb+srv://team-shiba:team-shib%40@cluster0.s4x0p.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
don't push credentials up to remote

2021-06-16 01:16 UTC, bonnieli commented on server/services/uploadService.js
> +export class UploadService{
seems unrelated to linting

2021-06-16 05:25 UTC, grayey commented on server/sample.env
> +MONGO_URI=mongodb+srv://team-shiba:team-shib%40@cluster0.s4x0p.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
This is noted. I have now added `sample.env` to gitignore.

2021-06-16 05:34 UTC, grayey commented on server/services/uploadService.js
> +export class UploadService{
Ok. In this branch, the specific commit that fixed linting was `https://github.com/hatchways/team-shiba/pull/40/commits/3424ebecb75dc3d01cbeff8969afaaaf546047b6`

2021-06-16 16:41 UTC, moffatethan commented on server/sample.env
> +MONGO_URI=mongodb+srv://team-shiba:team-shib%40@cluster0.s4x0p.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
@grayey You don't want to ignore the `sample.env`. This would cause more hassle if a future collaborator were to join a project.

2021-06-16 16:49 UTC, moffatethan commented on client/.eslintrc
> +   "prettier/prettier": ["error", { "endOfLine": "auto" }]
Could you please tell me what steps you made to solve the linting issues in the code before adding a workaround? Did you run a formatter on your file look into the linting scripts provided by eslint and prettier.

2021-06-16 16:54 UTC, moffatethan requested changes
@grayey I left you some comments to address, I don't see any linting issues here other than end of line formatting which can be addressed without adding a workaround.

Please refer to [here](https://prettier.io/docs/en/options.html#end-of-line) on why I want you to consider finding an alternative solution.

2021-06-16 17:25 UTC, grayey commented on server/sample.env
> +MONGO_URI=mongodb+srv://team-shiba:team-shib%40@cluster0.s4x0p.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
Ok, I see.

2021-06-22 15:29 UTC, rajivtitus reviewed
Hey Team! Please address the comments in this PR and make the necessary commits once changes are done.

2021-06-22 18:00 UTC, MillanAir commented on client/.eslintrc
> +   "prettier/prettier": ["error", { "endOfLine": "auto" }]
I used above steps to try and resolve my linting issues, This extra step doesn't give any errors however it doesn't have any effect on linting issues. Installing prettier and formatting document with prettier resolved the linting issues for me.

2021-06-24 17:17 UTC, merged