notifications model and controller
hatchways/team-shiba pull request #48
Opened 2021-06-18 18:40 UTC by rishabdhamija

### What this PR does (required):
- created notifications model and controller
- the following routes in routes/notification.js
       1. POST /notification/create
       2. GET /notification
       3. GET /notification/unread
       4. PATCH /notification/markRead/:id

### Screenshots / Videos (required):
-  for POST /notification/create, the title is first checked, if title exists already then notification is not saved.
![Screen Shot 2021-06-18 at 2 25 47 PM](https://user-images.githubusercontent.com/63626748/122602872-86ec0b00-d041-11eb-894c-e9a44c8a5e3b.png)
- if title is not present in any previous notification before, then it is saved.
![Screen Shot 2021-06-18 at 2 26 40 PM](https://user-images.githubusercontent.com/63626748/122602937-9f5c2580-d041-11eb-9050-baf7e1dff7bf.png)

- for READ /notification, it returns count as well as list of notifications
![Screen Shot 2021-06-18 at 2 30 32 PM](https://user-images.githubusercontent.com/63626748/122603041-c61a5c00-d041-11eb-95f4-96f284360a6d.png)

- for READ /notification/unread, it returns count as well as list of unread notifications. 
![Screen Shot 2021-06-18 at 2 31 40 PM](https://user-images.githubusercontent.com/63626748/122603130-eba76580-d041-11eb-8db3-2110c0a3b14b.png)

- for PATCH /notification/markRead/:id , it checks for a notification existing with the id, and if yes, changes the value of read field from false to true.
![Screen Shot 2021-06-18 at 2 36 32 PM](https://user-images.githubusercontent.com/63626748/122603634-a46da480-d042-11eb-900a-4b9e1b7a6c7b.png)

### Any information needed to test this feature (required):
-  http://localhost:3001/... routes as listed above,
- 
### Any issues with the current functionality (optional):
- The schema needs some updates as to differentiate notification from one user to another (like some foreign key referring back to user schema like in SQL)
- For testing purposes, during POST /notification/create, for date I used the following format:
 const date = new Date(); date.toISOString();
in the collection, the date is stored in the following format: ISODate("2021-06-18T16:40:48.534Z")

2021-06-22 16:10 UTC, rajivtitus commented on server/controllers/notification.js
> +    return res.status(201).json({
Status code 201 is for successful creation of a resource, maybe use 200 instead.

Reference: https://www.restapitutorial.com/httpstatuscodes.html

2021-06-22 16:10 UTC, rajivtitus commented on server/controllers/notification.js
> +      return res.status(201).json({ status: "no notifications" });
Ditto as above

2021-06-22 16:11 UTC, rajivtitus commented on server/controllers/notification.js
> +    res.status(201).json({ status: "notification marked as read." , notification: updateStatus });
Same here :)

2021-06-22 16:14 UTC, rajivtitus commented on server/controllers/notification.js
> +    if (notifications.length === 0) {
Since we are sending the notification count and notifications array in the response below (line 57), we can just conditionally display a message on the FE if there are no notifications, we can avoid checking the length here.

2021-06-22 16:22 UTC, rajivtitus commented on server/models/Notification.js
> +const notificationTypes = ["accepted", "declined", "upcoming"]
Are we planning to use this variable in the future? If you are only using it to show the types of notifications, you can use a comment instead :)

2021-06-22 16:31 UTC, rajivtitus commented on server/controllers/notification.js
> +    const titleTaken = await Notification.findOne({ title });
If we are creating notifications with unique titles this may pose as a problem. 
Eg: If one owner sends a message to two different sitters and if the title used is 'XYZ has sent you a message', then we will not be able to create notifications for both the messages sent.

2021-06-22 16:32 UTC, rajivtitus requested changes
Please review comments and address :)

2021-06-23 15:41 UTC, rishabdhamija commented on server/controllers/notification.js
> +    return res.status(201).json({
changed code to 200

2021-06-23 15:41 UTC, rishabdhamija commented on server/controllers/notification.js
> +      return res.status(201).json({ status: "no notifications" });
changed code to 200

2021-06-23 15:41 UTC, rishabdhamija commented on server/controllers/notification.js
> +    res.status(201).json({ status: "notification marked as read." , notification: updateStatus });
changed code to 200

2021-06-23 15:42 UTC, rishabdhamija commented on server/controllers/notification.js
> +    if (notifications.length === 0) {
removed the if statement testing notification.length (will be tested in FE as in instruction above)

2021-06-23 15:43 UTC, rishabdhamija commented on server/models/Notification.js
> +const notificationTypes = ["accepted", "declined", "upcoming"]
commented notification type for the time being (since it hasn't been decided whether the notification type will be from a list of types or a custom one)

2021-06-23 15:44 UTC, rishabdhamija commented on server/controllers/notification.js
> +    const titleTaken = await Notification.findOne({ title });
Removed title uniqueness testing from the contoller. Now, a userID is mentioned in the notification collection. The userID will be referencing to the created (signedup) user so uniqueness will be taken care by that.

2021-06-23 16:24 UTC, rishabdhamija commented
I have removed package-lock.json and yark-lock.json files from my PR since they were conflicting with the ones in main. During merging I will include them so that only the main ones remain in place. That is the reason ci/circleci: build-and-test failed above.

2021-06-23 17:51 UTC, rajivtitus approved these changes
LGTM! 

Please resolve any conflicts before merging

2021-06-23 18:07 UTC, merged