Request model controller
hatchways/team-shiba pull request #50
Opened 2021-06-21 16:02 UTC by grayey

### What this PR does (required):
- This feature adds the request model and request controller

### Screenshots / Videos (required):
- 

https://user-images.githubusercontent.com/26135612/122785038-ed279680-d2aa-11eb-9afe-d9caf31c9fe7.mp4

![image](https://user-images.githubusercontent.com/26135612/122791939-9a051200-d2b1-11eb-8d56-3d92b686adc2.png)

### Any information needed to test this feature (required):
- visit http://localhost:3001/api-docs.
- Test: GET requests/sitter, GET/POST requests/owner, GET requests/:id

### Any issues with the current functionality (optional):
- Update(PUT) requests is ongoing

2021-06-22 19:45 UTC, rajivtitus reviewed
Hey Team! Can we please adjust the base of this PR? You can do so by clicking 'Edit' on the top right corner and change the base branch from 'main' to the branch you based your PR on. Thanks!

2021-06-23 00:52 UTC, rajivtitus commented on client/src/context/useAuthContext.tsx
> +      // history.push('/dashboard');
remove commented code

2021-06-23 00:53 UTC, rajivtitus commented on client/src/context/useAuthContext.tsx
> +          // history.push('/dashboard');
Can we uncomment this? As we need the user to be redirected to the listings/dashboard page upon login

2021-06-23 00:53 UTC, rajivtitus commented on client/src/pages/Dashboard/Profile/ProfilePhoto.tsx
> +    // borderRadius: 12,
remove unused styles

2021-06-23 00:54 UTC, rajivtitus commented on client/src/pages/Dashboard/Profile/ProfilePhoto.tsx
> +            <h2>Profile Photo</h2>
Since we using Material UI, you can replace the h2 tags with Typography here.

2021-06-23 00:58 UTC, rajivtitus commented on server/controllers/request.js
> +
Currently we not handling error in any of the controllers, please use a try/catch block to handle errors.

2021-06-23 00:58 UTC, rajivtitus commented on server/controllers/request.js
> +
Same as above

2021-06-23 01:00 UTC, rajivtitus requested changes
Please review comments and address

2021-06-23 01:27 UTC, grayey commented on server/controllers/request.js
> +
Done now

2021-06-23 01:27 UTC, grayey commented on server/controllers/request.js
> +
This is done now.

2021-06-23 20:59 UTC, rajivtitus commented on server/controllers/request.js
> +  const { ownerId } = req.query;
Query parameters are used when searching through the database.

Please see for reference: https://coursework.vschool.io/express-params-and-query/

2021-06-23 20:59 UTC, rajivtitus commented on server/controllers/request.js
> +  const { sitterId } = req.query;
Same as above

2021-06-23 21:05 UTC, grayey commented on server/controllers/request.js
> +  const { sitterId } = req.query;
Yes, thanks. I'll change all those back to use params or body.

2021-06-23 21:06 UTC, grayey commented on server/controllers/request.js
> +  const { ownerId } = req.query;
Yea, thanks. At the time, I wanted to quickly test.

2021-06-23 21:16 UTC, rajivtitus approved these changes
There seems to be code (which has been reviewed in earlier PRs) from other branches which is not related to the Request Model/Controllers. However, please remove commented code as per comments. Once you merge with main, test routes once again to make sure everything is working.

2021-06-24 17:27 UTC, closed without merging