added demo user
hatchways/team-shiba pull request #55
Opened 2021-06-22 17:56 UTC by MillanAir

### What this PR does (required):
- Added Protected Route functionality and Demo User Login

### Screenshots / Videos (required):
![image](https://user-images.githubusercontent.com/4408002/122975417-8ceb3000-d350-11eb-9529-d15169bed1d4.png)

Demo User:
![image](https://user-images.githubusercontent.com/4408002/122975489-a12f2d00-d350-11eb-82fb-d1aaf63417cc.png)

### Any information needed to test this feature (required):
- If user wants to browse a protected page then they need to log in first.

### Any issues with the current functionality (optional):
- Demo User login details aren't working fully. Needs extra information regarding the flow of login

2021-06-25 16:41 UTC, rajivtitus requested changes

2021-06-25 16:41 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +  (handleSubmit = (e) => {
1. Please add another button the Login Form called 'Demo Login'
2. Once completed, create a function to handle button click and use the `login()` function in the helpers folder and pass the demo user credentials as arguments.
3. Finally, reference the function in the button's onClick property :)

2021-06-29 15:15 UTC, MillanAir commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +  (handleSubmit = (e) => {
Thanks for the support Rajiv, I added the functionality in login Form as per your steps mentioned. Thanks.

2021-06-29 18:13 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +    alert('Demo Login Works');
You can remove this alert as the snack bar will be updated if there's an error and if there are no errors the user will be redirected to the dashboard.

2021-06-29 18:14 UTC, rajivtitus approved these changes
Looks good to me!

2021-06-29 19:42 UTC, MillanAir commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +    alert('Demo Login Works');
ok sure

2021-06-29 21:02 UTC, merged