messages, conversations model and controllers
hatchways/team-shiba pull request #56
Opened 2021-06-24 17:27 UTC by rishabdhamija

### What this PR does (required):
- message and conversation model

### Screenshots / Videos (required):
- Post at least one screenshot to show the feature in action

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-06-25 16:05 UTC, rajivtitus commented on server/controllers/message.js
> +    if (!messageSaved) {
We don't need this if clause, if there's an error saving document to DB then it will be caught in the catch block.

2021-06-25 16:06 UTC, rajivtitus commented on server/controllers/message.js
> +exports.createMessage =  asyncHandler(async (req, res, next) => {
Please refer to Message model and update controller accordingly, we also need to add the 'sender' while we create a message :)

2021-06-25 16:07 UTC, rajivtitus commented on server/models/Message.js
> +  receiverID: {
I don't think we need to keep track of the receiver, as the logged in user can be found within the participants in the conversation.

2021-06-25 16:10 UTC, rajivtitus commented on server/controllers/conversation.js
> +  console.log("this is the req body " , data);
please remove

2021-06-25 16:12 UTC, rajivtitus commented on server/controllers/conversation.js
> +  console.log("this is the convID " , convID);
please remove

2021-06-25 16:12 UTC, rajivtitus commented on server/controllers/conversation.js
> +    console.log("this is the conversationList " , conversationList);
please remove

2021-06-25 16:14 UTC, rajivtitus commented on server/controllers/conversation.js
> +exports.getConversationList = asyncHandler( async (req, res, next) => {
Please modify the controller so that we only get conversations which the logged in user is a part of. The way it is currently setup will give us all the conversations :)

2021-06-25 16:17 UTC, rajivtitus commented on server/controllers/conversation.js
> +exports.getDetailedConversation = asyncHandler( async (req, res, next) => {
Maybe you can add the logic to get participant information to the `getMessagesConversation` controller.

2021-06-25 16:18 UTC, rajivtitus commented on server/models/Message.js
> +    ref: 'User',
My suggestion would be to reference Profile, as we can get 'names, photos etc'. However, referencing users is fine too :)

2021-06-25 16:19 UTC, rajivtitus requested changes
Good effort! 

Please review comments and address. Thank  you

2021-06-28 16:07 UTC, rishabdhamija commented on server/models/Message.js
> +  receiverID: {
I have a hypothetical situation. Perhaps I might be able to picture the situation better with that. Let's say the user logged in is dummy1. so, if a conversation begins between dummy1 as well as another user, how will I differentiate in messages as who sent the message and who received the message, in case multiple messages are exchanged between them. It could be that I am misunderstanding the situation.

2021-06-28 16:47 UTC, rajivtitus commented on server/models/Message.js
> +  receiverID: {
We have two participants in our conversation, the user who's logged in will be the sender and the other participant will be the receiver (You can differentiate the messages by checking the logged in user's id with the list of participants). Please let me know if that answers your question? :)

2024-11-29 16:20 UTC, closed without merging